name: Build

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          # - name: i686-pc-windows-msvc
          #   arch: x86
          - name: x86_64-pc-windows-msvc
            arch: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target.name }}
          override: true
          profile: minimal

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "wasabi-windows-${{ matrix.target.arch }}"
          path: "target/${{ matrix.target.name }}/release/wasabi.exe"

  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Move files
        run: |
          mkdir out
          for dir in ./artifacts/*; do
            for file in $dir/*; do
              mv $dir/* ./out/${dir##*/}${file##*/wasabi}
            done
          done

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          body: A new draft release.
          draft: true
          files: ./out/*
